name = "smtd-cron-notifier"
main = "index.ts"
compatibility_date = "2024-12-01"

[triggers]
# JST 9:00 = UTC 0:00
# JST 12:00 = UTC 3:00
# JST 21:00 = UTC 12:00
crons = ["0 0 * * *", "0 3 * * *", "0 12 * * *"]
